server:
  port: 8080
spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username:
    password:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.qq.com
    username:
    # 授权码
    password:
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    protocol: smtps
  # RabbitMQ 配置
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3 #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）
        acknowledge-mode: auto

p6spy:
  config:
    appender: com.p6spy.engine.spy.appender.Slf4JLogger
    logMessageFormat: com.p6spy.engine.spy.appender.CustomLineFormat
    customLogMessageFormat: executionTime:%(executionTime)| 执行sql:%(sql)

#资源上传
upload:
  oss:
    endpoint:
    accessKeySecret:
    accessKeyId:
    bucketName:

